# Generated by Django 3.1.5 on 2021-03-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('bidding_start', models.DecimalField(decimal_places=2, max_digits=19)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
