# Generated by Django 3.1.5 on 2021-03-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='is_user_listing_owner',
            field=models.BooleanField(default=False),
        ),
    ]
