# Generated by Django 3.1.5 on 2021-03-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bidding_is_user_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='is_auction_winner',
            field=models.BooleanField(default=False),
        ),
    ]
